blank_issues_enabled: false
contact_links:
  - name: Question or help
    url: https://github.com/Lemkinator/OneUI-Sample-App/discussions/new?category=q-a
    about: Ask questions and get help in Discussions.
