name: Feature request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Before you suggest
      options:
        - label: I searched the existing issues, including closed ones.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What should happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you considered
