name: Build

on:
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
